---
version: "3.4"
services:
  messaging:
    depends_on:
      - redis
    image: "uwcirg/isacc_messaging_backend:${DOCKER_IMAGE_TAG:-latest}"
    build:
      context: .
    volumes:
      - ./:/opt/app
      # mount host certificate bundle into container
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
      # mount host hosts file into container
      - /etc/hosts:/etc/hosts:ro
    ports:
      # allow override of published port
      - ${P_PORT:-8000}:8000
    environment:
      REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
      SESSION_REDIS: redis://redis:6379/0
    env_file:
      - messaging.env

  redis:
    image: redis
